export const DIGIT_ENTERED = 'DIGIT_ENTERED';
export const OPERATOR_ENTERED = 'OPERATOR_ENTERED';
export const COMPUTE_RESULT = 'COMPUTE_RESULT';
export const CLEAR_ALL = 'CLEAR_ALL';
export const RESET_IS_DIGIT_LIMIT_MET = 'RESET_IS_DIGIT_LIMIT_MET';
